name: CI
on:
  push:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  TZ: "Europe/Helsinki"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shards: [ 1 ]
        total_shards: [ 1 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Run tests
        run: ./run-tests.sh
        env:
          PLAYWRIGHT_SHARD: ${{ matrix.shards }}
          PLAYWRIGHT_TOTAL_SHARDS: ${{ matrix.total_shards }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7.0.0
        with:
          name: test-results-${{ matrix.shards }}
          path: test-results
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: production
      url: https://sis-u-bot.alanen.dev
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v6.0.2
      - name: Configure OpenTofu for Terraform
        uses: opentofu/setup-opentofu@v2.0.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: deploy.sh
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: ./deploy.sh
